const p=(id,name,kind,lat,lng,address,color,time,short,why,facts=[],price="",tone="")=>({id,name,kind,lat,lng,address,color,time,short,why,facts,price,tone});
const days={
 D1:{date:"9/10 周四",title:"温泉初遇",summary:"落地后直接去清河半岛，把第一天留给泡汤、吃饭和安静睡一晚。",stay:"清河半岛主楼 5 楼豪华双床温泉套房",stayNote:"2 × 1.8m · 主楼电梯直达温泉 · 订单确认四早四票",total:"¥2,100–2,200",note:"套房订单若明确含四张温泉票与四份早餐，不再另购三人温泉票。",nodes:[
  p("airport","沈阳桃仙机场","抵达",41.637010,123.486593,"浑南区桃仙街道","#356f67","11:15","落地出发","只带随身行李，三人直接网约车前往清河半岛，减少换乘。",[["交通","三人网约车优先"],["航班","MU2827 候选"],["提醒","时刻以订单为准"]],"机票另计"),
  p("qinghe","清河半岛温泉","温泉体验",41.933779,123.427358,"沈北新区蒲南路20号","#df765e","13:00","换衣、泡汤、户外池","东北洗浴体验安排在刚落地的第一天，下午先泡、晚上私汤，恢复体力。",[["看点","户外温泉 / 无边池 / 汗蒸"],["餐饮","三楼单点，别默认自助"],["避雷","不住公共休息区"]],"已计入套房","warm"),
  p("room","豪华双床温泉套房","安静过夜",41.933930,123.427640,"清河半岛主楼 5 楼","#d6a54b","15:00","入住、晚餐、夜泡","两张大床让三人同住不拥挤；主楼电梯上下温泉，不走别墅区。",[["床型","2 × 1.8m"],["早餐","订单称含四早"],["温泉","订单称含四票"],["核对","以付款页权益为准"]],"¥2,100–2,200","warm") ]},
 D2:{date:"9/11 周五",title:"盛京旧城",summary:"一条步行友好的历史主轴：故宫、帅府、中街，中间只安排一顿坐下慢吃的午饭。",stay:"中街故宫亚朵 S · 尊享家庭房",stayNote:"1.8m + 1.2m · 高楼层、无烟、远离电梯",total:"¥650–850",note:"当日价格为市区酒店两晚预算的单晚拆分；门票与餐饮另计。",nodes:[
  p("atour","中街故宫亚朵 S","市区住宿",41.795700,123.448800,"沈河区朝阳街127号","#356f67","09:30","寄存行李","故宫、帅府和中街都在步行圈；家庭房把舒适和便利放在第一位。",[["入住","9/11–9/13"],["房型","1.8m + 1.2m"],["备注","高楼层 / 无烟 / 远离电梯"]],"约 ¥650–850 / 晚"),
  p("palace","沈阳故宫","清初皇宫",41.796113,123.449644,"沈河区沈阳路171号","#d6a54b","10:00","大政殿、十王亭、凤凰楼","盛京历史的核心。清初宫廷建筑紧凑，适合用讲解把看点串成一条线。",[["开放基线","08:30–17:00"],["停止入馆","16:15"],["预约","官方渠道 / 身份证"],["建议","开门入场 + 讲解"]],"门票另计"),
  p("marshal","张氏帅府","民国建筑群",41.792111,123.451670,"沈河区朝阳街少帅府巷46号","#df765e","13:30","大青楼、老虎厅","从清代皇宫接到张作霖、张学良的近代史；通票可连赵一荻故居与金融馆。",[["建议","通票按顺序逛完"],["看点","大青楼 / 老虎厅"],["讲解","推荐"],["提醒","出馆后通常不可再入"]],"门票另计"),
  p("zhongjie","中街","老城烟火",41.798969,123.454381,"沈河区中街路","#356f67","16:30","冰点、晚餐、散步","历史参观后的轻松收尾；按胃口选择甜品和晚餐，不再加远景点。",[["甜品","中街冰点一楼"],["晚餐","老四季候选"],["避雷","主街网红小吃溢价"]],"餐饮约 ¥180–260") ]},
 D3:{date:"9/12 周六",title:"历史与西塔",summary:"从历史记忆走进铁西工业，再以西塔晚餐收尾；1905 只做短歇，不占掉晚餐体力。",stay:"中街故宫亚朵 S · 尊享家庭房",stayNote:"继续连住，免去换酒店与拖行李",total:"¥650–850",note:"当日价格为市区酒店两晚预算的单晚拆分；预约/餐饮另计。",nodes:[
  p("918","九一八历史博物馆","历史记忆",41.834199,123.461502,"大东区望花南街46号","#2e4758","09:00","肃穆参观、听讲解","沈阳最有历史分量的地点之一，安排在上午更完整；建议以讲解理解时间线。",[["开放基线","09:00–17:00"],["停止入馆","16:30"],["预约","易游沈阳"],["提醒","带身份证，不摆拍"]],"免费预约","dark"),
  p("industry","中国工业博物馆","铁西工业",41.818950,123.349191,"铁西区卫工北街14号","#df765e","11:45","机床、铸造馆、厂房","巨型机床与厂房空间，把沈阳工业城市记忆变成很直观的实景。",[["门票","通常免费"],["预约","公众号 / 美团当周复核"],["穿着","舒适鞋"],["节奏","控制在 2 小时内"]],"通常免费"),
  p("1905","1905 文创园","旧厂房短歇",41.809895,123.376247,"铁西区兴华北街8号","#d6a54b","14:30","咖啡、拍照、短歇","它不是必须久逛的景点；用来转换节奏、喝咖啡、拍一组工业风照片。",[["作用","短歇 / 咖啡"],["画面","旧厂房工业风"],["提醒","看当日营业"]],"咖啡约 ¥60–100"),
  p("xita","西塔朝鲜族风情街","晚间美食",41.802444,123.402405,"和平区西塔街 / 安图街一带","#356f67","17:00","先打糕，后共享鳗鱼","全程最值得专门安排的一顿晚餐。热门打糕先买，烤鳗鱼作为三人共享主餐。",[["先买","师任堂打糕 / 饭团"],["主餐","味家烤鳗鱼共享"],["加餐","最多 1–2 份"],["避雷","不做七店通关 / 避拉客店"]],"餐饮约 ¥500–650") ]},
 D4:{date:"9/13 周日",title:"轻松返程",summary:"睡到自然醒，买好伴手礼，15:30 从中街出发去机场；不再硬塞景点。",stay:"中午退房 · 前台寄存行李",stayNote:"轻装逛中街；下午直接去桃仙机场",total:"¥250–450",note:"主要为市内交通、伴手礼前的轻餐和机场时间预留；伴手礼按实际购买。",nodes:[
  p("hotelout","市区酒店退房","慢启动",41.795700,123.448800,"沈河区朝阳街127号","#356f67","上午","退房、寄存行李","最后一天不赶早；退房后寄存行李，轻装逛中街。",[["退房","12:00 前为准"],["行李","前台寄存"],["原则","不排远景点"]],"已含在住宿"),
  p("souvenir","中街伴手礼","本地味道",41.798969,123.454381,"沈河区中街路","#d6a54b","中午","不老林、八王寺等","选择正规超市或老字号，轻松买完就回机场，不把时间耗在景区礼盒上。",[["推荐","不老林 / 八王寺"],["冷链","香肠按返程时间买"],["避雷","景区花哨礼盒"]],"按实际购买"),
  p("return","沈阳桃仙机场","返程",41.637010,123.486593,"浑南区桃仙街道","#2e4758","15:30","值机、安检、登机","预留充足时间，直飞返宁。中街地铁要在青年大街换乘 2 号线；三人打车更省心。",[["航班","HO1712 候选"],["起飞","18:35"],["交通","地铁换乘或打车"],["提醒","时刻以订单为准"]],"机票另计","dark") ]}
};
let dayKey="D1",selected=null;
const map=L.map("route-map",{scrollWheelZoom:true,zoomControl:true}).setView([41.81,123.42],11);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);
const svg=d3.select(map.getPanes().overlayPane).append("svg").attr("class","d3-map-overlay"), layer=svg.append("g").attr("class","leaflet-zoom-hide"),tooltip=document.querySelector("#map-tooltip");
function tabs(){document.querySelector("#day-tabs").innerHTML=Object.entries(days).map(([k,d])=>`<button class="day-tab ${k===dayKey?"active":""}" data-day="${k}"><b>${k}</b><small>${d.date}</small></button>`).join("");document.querySelectorAll(".day-tab").forEach(b=>b.onclick=()=>selectDay(b.dataset.day));}
function dayPanel(){const d=days[dayKey];document.querySelector("#sidebar-content").innerHTML=`<section class="day-heading"><p class="eyebrow">${d.date}</p><h2>${d.title}</h2><p class="summary-copy">${d.summary}</p></section><section class="day-card stay-card"><h3>今晚住哪里</h3><b>${d.stay}</b><span>${d.stayNote}</span></section><section class="day-card"><div class="price-row"><span>当天基础开销</span><b>${d.total}</b></div><p class="inline-note">${d.note}</p></section><section class="day-card"><h3>今天怎么走</h3><ol class="route-list">${d.nodes.map(n=>`<li><button class="route-step" data-node="${n.id}"><time>${n.time}</time><span><b>${n.name}</b><span>${n.short}</span></span></button></li>`).join("")}</ol></section>`;document.querySelectorAll(".route-step").forEach(b=>b.onclick=()=>showPlace(days[dayKey].nodes.find(n=>n.id===b.dataset.node)));}
function placePanel(n){document.querySelector("#sidebar-content").innerHTML=`<button class="back-button" id="back-day">← 返回当天行程</button><section class="place-hero ${n.tone}"><span class="kind">${n.kind} · ${n.time}</span><h2>${n.name}</h2><p class="address">${n.address}</p></section><section class="place-section"><h3>为什么来这里</h3><p>${n.why}</p></section><section class="place-section"><h3>看点与安排</h3><div class="fact-grid">${n.facts.map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}</div>${n.price?`<div class="place-price">这一站预算 <b>${n.price}</b></div>`:""}</section>`;document.querySelector("#back-day").onclick=()=>{selected=null;dayPanel();draw();};}
function showPlace(n){selected=n;placePanel(n);map.panTo([n.lat,n.lng],{animate:true,duration:.45});draw();}
function hover(n,event){tooltip.hidden=false;tooltip.innerHTML=`<small>${n.kind} · ${n.time}</small><b>${n.name}</b><span>${n.short}</span>`;const r=document.querySelector(".map-stage").getBoundingClientRect();tooltip.style.left=`${Math.min(event.clientX-r.left+14,r.width-240)}px`;tooltip.style.top=`${Math.max(16,event.clientY-r.top-66)}px`;}
function draw(){const ns=days[dayKey].nodes,pts=ns.map(n=>map.latLngToLayerPoint([n.lat,n.lng])),b=map.getBounds(),nw=map.latLngToLayerPoint(b.getNorthWest()),se=map.latLngToLayerPoint(b.getSouthEast());svg.attr("width",se.x-nw.x).attr("height",se.y-nw.y).style("left",`${nw.x}px`).style("top",`${nw.y}px`);layer.attr("transform",`translate(${-nw.x},${-nw.y})`);layer.selectAll("path.edge").data(d3.pairs(pts)).join("path").attr("class","edge").attr("d",e=>`M${e[0].x},${e[0].y} L${e[1].x},${e[1].y}`);const groups=layer.selectAll("g.node").data(ns,n=>n.id),enter=groups.enter().append("g").attr("class","node").style("opacity",0).on("click",(_,n)=>showPlace(n)).on("mousemove",(e,n)=>hover(n,e)).on("mouseleave",()=>tooltip.hidden=true);enter.append("circle");enter.append("text").attr("class","node-title").attr("text-anchor","middle");enter.append("text").attr("class","node-time").attr("text-anchor","middle");const all=enter.merge(groups);all.attr("transform",(_,i)=>`translate(${pts[i].x},${pts[i].y})`).transition().duration(250).style("opacity",1);all.select("circle").attr("r",n=>selected?.id===n.id?25:18).attr("fill",n=>n.color);all.select(".node-title").attr("y",-28).text(n=>n.name);all.select(".node-time").attr("y",39).text(n=>n.time);groups.exit().remove();}
function selectDay(key){dayKey=key;selected=null;tabs();dayPanel();const bound=L.latLngBounds(days[key].nodes.map(n=>[n.lat,n.lng]));map.fitBounds(bound.pad(.18),{animate:true,duration:.6,maxZoom:13});setTimeout(draw,650);}
map.on("moveend zoomend",draw);tabs();selectDay("D1");
