const trip=window.TRIP_CONFIG,{nodes,days,categories}=trip;
const state={day:"ALL",mode:"overview",selected:null,filters:new Set(Object.keys(categories))};
const categoryColors={transport:"#3f6e8a",stay:"#3f806d",food:"#dc795d",sight:"#c99d45",experience:"#9b6eaa",shopping:"#b98241"};
const photoMap={palace:["https://upload.wikimedia.org/wikipedia/commons/8/84/Mukden_Palace_01.jpg","沈阳故宫 · Wikimedia Commons"],marshal:["https://upload.wikimedia.org/wikipedia/commons/a/a5/%E6%B2%88%E9%98%B3%E5%BC%A0%E6%B0%8F%E5%B8%85%E5%BA%9C%E5%A4%A7%E9%9D%92%E6%A5%BC2024.10_%281%29.jpg","张氏帅府 · Wikimedia Commons"],industry:["https://upload.wikimedia.org/wikipedia/commons/6/61/Interior_of_China_Industrial_Museum_in_Shenyang.jpg","中国工业博物馆 · Wikimedia Commons"],xita:["https://upload.wikimedia.org/wikipedia/commons/9/9d/Business_on_Xita_Street_20260330173055.jpg","西塔街区 · Wikimedia Commons"],museum918:["https://upload.wikimedia.org/wikipedia/commons/7/79/%E6%B2%88%E9%98%B3%E2%80%9C%E4%B9%9D%E4%B8%80%E5%85%AB%E2%80%9D%E5%8E%86%E5%8F%B2%E5%8D%9A%E7%89%A9%E9%A6%86%E5%B1%95%E7%A4%BA%E7%9A%84%E5%B9%B3%E9%A1%B6%E5%B1%B1%E6%9D%91%E5%A4%8D%E5%8E%9F%E6%A8%A1%E5%9E%8B.jpg","九一八历史博物馆展陈 · Wikimedia Commons"]};
document.querySelector("#trip-title").textContent=trip.meta.title;document.querySelector("#trip-dates").textContent=trip.meta.dates;
const PI=Math.PI,A=6378245,EE=.00669342162296594323;
function outside(lng,lat){return lng<72.004||lng>137.8347||lat<.8293||lat>55.8271}function tLat(x,y){let r=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));r+=(20*Math.sin(6*x*PI)+20*Math.sin(2*x*PI))*2/3;r+=(20*Math.sin(y*PI)+40*Math.sin(y/3*PI))*2/3;return r+(160*Math.sin(y/12*PI)+320*Math.sin(y*PI/30))*2/3}function tLng(x,y){let r=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));r+=(20*Math.sin(6*x*PI)+20*Math.sin(2*x*PI))*2/3;r+=(20*Math.sin(x*PI)+40*Math.sin(x/3*PI))*2/3;return r+(150*Math.sin(x/12*PI)+300*Math.sin(x/30*PI))*2/3}function toGcj(lng,lat){if(outside(lng,lat))return[lng,lat];let dlat=tLat(lng-105,lat-35),dlng=tLng(lng-105,lat-35),rad=lat/180*PI,magic=Math.sin(rad);magic=1-EE*magic*magic;const sq=Math.sqrt(magic);dlat=dlat*180/((A*(1-EE))/(magic*sq)*PI);dlng=dlng*180/(A/sq*Math.cos(rad)*PI);return[lng+dlng,lat+dlat]}
const map=new AMap.Map("route-map",{viewMode:"2D",zoom:11,center:toGcj(123.42,41.81),mapStyle:"amap://styles/whitesmoke",resizeEnable:true,showLabel:true});map.addControl(new AMap.ToolBar({position:{top:"110px",right:"12px"}}));
const svg=d3.select(map.getContainer()).append("svg").attr("class","d3-map-overlay").attr("width","100%").attr("height","100%"),layer=svg.append("g"),tooltip=document.querySelector("#map-tooltip");
function dayFor(id){return days.find(d=>d.id===id)}function activeDays(){return state.day==="ALL"?days:[dayFor(state.day)]}function stops(){return activeDays().flatMap(day=>day.stops.map((stop,index)=>({...stop,day,index,nodeData:nodes[stop.node]})))}function isVisible(n){return n.categories.some(c=>state.filters.has(c))}function visibleStops(){return stops().filter(x=>isVisible(x.nodeData))}
function dayTabs(){document.querySelector("#day-tabs").innerHTML=[`<button class="day-tab ${state.day==="ALL"?"active":""}" data-day="ALL"><b>全程</b><small>4 天</small></button>`,...days.map(d=>`<button class="day-tab ${state.day===d.id?"active":""}" data-day="${d.id}"><b>${d.id}</b><small>${d.date.split(" ")[0]}</small></button>`)].join("");document.querySelectorAll(".day-tab").forEach(b=>b.onclick=()=>selectDay(b.dataset.day));}
function controls(){document.querySelector("#detail-toggle").innerHTML=[['overview','概览'],['detail','详细时间表']].map(([id,label])=>`<button class="${state.mode===id?"active":""}" data-mode="${id}">${label}</button>`).join("");document.querySelectorAll("#detail-toggle button").forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});const panel=document.querySelector("#filter-panel");panel.hidden=false;panel.innerHTML=`<div class="filter-label"><span>地图显示</span><button id="filter-all">全选</button></div><div class="filter-chips">${Object.entries(categories).map(([id,label])=>`<button class="filter-chip ${state.filters.has(id)?"active":""}" data-category="${id}"><i style="background:${categoryColors[id]}"></i>${label}</button>`).join("")}</div>`;document.querySelector("#filters-button").onclick=()=>{state.filters=new Set(Object.keys(categories));render()};document.querySelector("#filter-all").onclick=()=>{state.filters=new Set(Object.keys(categories));render()};document.querySelectorAll(".filter-chip").forEach(b=>b.onclick=()=>{const c=b.dataset.category;state.filters.has(c)?state.filters.delete(c):state.filters.add(c);render()})}
function tagList(n){return n.categories.map(c=>`<span class="tag"><i style="background:${categoryColors[c]}"></i>${categories[c]}</span>`).join("")}
function overviewPanel(){const all=state.day==="ALL",selected=activeDays(),stays=[...new Map(days.filter(d=>d.stayNode).map(d=>[d.stayNode,d])).values()];return `<section class="panel-title"><p class="eyebrow">${all?"全程 · 4 天":"${selected[0].id} · ${selected[0].date}"}</p><h2>${all?"完整行程总览":selected[0].title}</h2><p>${all?"下方四张卡是每天的路线；点“详细时间表”可一次看全程所有时间与交通。":selected[0].summary}</p></section>${all?`<section class="overview-metrics"><div><small>🗓 行程</small><b>${days.length} 天</b></div><div><small>🛏 住宿</small><b>${stays.length} 处</b></div><div><small>¥ 基础预算</small><b>8.2–9.0k</b></div></section>`:""}<section class="section-block"><h3>${all?"每天路线":"当天路线"}</h3><div class="day-overview-list">${selected.map(d=>`<button class="day-overview" data-jump="${d.id}"><span class="day-label">${d.id} · ${d.date}</span><b>${d.title}</b><p>${d.summary}</p><small>🛏 ${d.stay} · ¥ ${d.dailyBudget}</small></button>`).join("")}</div></section><section class="section-block"><h3>住宿</h3><div class="stay-list">${stays.map(d=>{const n=nodes[d.stayNode];const bed=n.facts.find(x=>x[0]==="床型")?.[1]||n.facts.find(x=>x[0]==="房型")?.[1]||"房型待确认";return `<button class="stay-summary" data-node="${d.stayNode}"><span>🛏 ${d.id}${d.id==="D1"?" · 1晚":" · 2晚"}</span><b>${d.stay}</b><small>🛌 ${bed} · ¥ ${n.price}</small></button>`}).join("")}</div></section>`}
function detailPanel(){const selected=activeDays();return `<section class="panel-title"><p class="eyebrow">${state.day==="ALL"?"按时间串起全程":"详细时间表"}</p><h2>${state.day==="ALL"?"四天详细行程":selected[0].title}</h2><p>包含交通方式与建议用时；灰色步骤表示被当前筛选隐藏。</p></section><section class="section-block detailed-days">${selected.map(day=>`<article class="detailed-day"><header><span>${day.id} · ${day.date}</span><b>${day.title}</b></header><ol>${day.stops.map((stop,i)=>{const n=nodes[stop.node],on=isVisible(n);return `<li class="${on?"":"muted-step"}"><button data-node="${stop.node}"><time>${stop.time}</time><span><b>${n.name}</b><small>${stop.detail}</small></span></button>${i<day.stops.length-1?`<div class="transfer">↳ ${day.stops[i+1].mode}${day.stops[i+1].duration?` · ${day.stops[i+1].duration}`:""}</div>`:""}</li>`}).join("")}</ol><footer><span>住：${day.stay}</span><b>${day.dailyBudget}</b></footer></article>`).join("")}</section>`}
function placePanel(n){const id=Object.entries(nodes).find(([,v])=>v===n)?.[0],photo=photoMap[id],media=photo?`<figure class="place-photo"><img src="${photo[0]}" alt="${n.name}" loading="lazy"><figcaption>${photo[1]}</figcaption></figure>`:`<div class="place-photo photo-fallback"><span>${tagList(n)}</span><b>${n.name}</b><small>地点介绍由旅行配置提供</small></div>`;return `<button class="back-button" id="back-view">← 返回${state.mode==="detail"?"详细行程":"总览"}</button><section class="place-hero ${n.tone||""}"><div class="tag-row">${tagList(n)}</div><h2>${n.name}</h2><p class="address">${n.address}</p></section>${media}<section class="place-section"><h3>介绍</h3><p>${n.intro}</p></section><section class="place-section"><h3>为什么安排</h3><p>${n.why}</p></section><section class="place-section"><h3>你需要知道</h3><div class="fact-grid">${n.facts.map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}</div><div class="place-price">这一站预算 <b>${n.price||"待确认"}</b></div></section>`}
function bindPanel(){document.querySelectorAll("[data-node]").forEach(b=>b.onclick=()=>showPlace(nodes[b.dataset.node]));document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>selectDay(b.dataset.jump));const back=document.querySelector("#back-view");if(back)back.onclick=()=>{state.selected=null;render()}}
function render(){dayTabs();controls();document.querySelector("#sidebar-content").innerHTML=state.selected?placePanel(state.selected):(state.mode==="detail"?detailPanel():overviewPanel());bindPanel();draw()}
function showPlace(n){state.selected=n;map.panTo(toGcj(n.lng,n.lat));render()}function hover(n,event){tooltip.hidden=false;tooltip.innerHTML=`<small>${tagList(n)}</small><b>${n.name}</b><span>${n.short}</span>`;const r=document.querySelector(".map-stage").getBoundingClientRect();tooltip.style.left=`${Math.min(event.clientX-r.left+14,r.width-240)}px`;tooltip.style.top=`${Math.max(16,event.clientY-r.top-66)}px`}
function draw(){const unique=new Map;visibleStops().forEach(x=>unique.set(x.node,x.nodeData));const visible=[...unique.values()],points=new Map(visible.map(n=>[n,map.lngLatToContainer(toGcj(n.lng,n.lat))]));const edges=activeDays().flatMap(day=>d3.pairs(day.stops.map(s=>nodes[s.node])).filter(([a,b])=>points.has(a)&&points.has(b)).map(([a,b])=>({a,b,day})));layer.selectAll("path.edge").data(edges,e=>`${e.day.id}-${e.a.name}-${e.b.name}`).join("path").attr("class","edge").attr("stroke",e=>e.day.id==="D1"?"#8b9c9a":"#356f67").attr("d",e=>{const a=points.get(e.a),b=points.get(e.b);return `M${a.x},${a.y} L${b.x},${b.y}`});const groups=layer.selectAll("g.node").data(visible,n=>n.name),enter=groups.enter().append("g").attr("class","node").style("opacity",0).on("click",(_,n)=>showPlace(n)).on("mousemove",(e,n)=>hover(n,e)).on("mouseleave",()=>tooltip.hidden=true);enter.append("circle");enter.append("text").attr("class","node-title").attr("text-anchor","middle");enter.append("text").attr("class","node-time").attr("text-anchor","middle");const all=enter.merge(groups);all.attr("transform",n=>{const p=points.get(n);return `translate(${p.getX()},${p.getY()})`}).transition().duration(250).style("opacity",1);all.select("circle").attr("r",n=>state.selected===n?25:18).attr("fill",n=>categoryColors[n.categories[0]]||"#356f67");all.select(".node-title").attr("y",-28).text(n=>n.name);all.select(".node-time").attr("y",39).text(n=>visibleStops().find(x=>x.nodeData===n)?.time||"");groups.exit().remove()}
function selectDay(id){state.day=id;state.selected=null;const view=id==="ALL"?{lng:123.42,lat:41.8,zoom:10}:dayFor(id).view;map.setZoomAndCenter(view.zoom,toGcj(view.lng,view.lat));render();setTimeout(draw,650)}
map.on("mapmove",draw);map.on("moveend",draw);map.on("zoomend",draw);map.on("complete",draw);render();selectDay("ALL");
