const p = (id,name,kind,lat,lng,address,color,time,why,facts=[],tone="") => ({id,name,kind,lat,lng,address,color,time,why,facts,tone});
const days = {
  D1:{title:"D1 · 温泉初遇",caption:"南京落地后直接进入温泉主楼：不赶市区，把第一晚留给恢复体力。",nodes:[
    p("airport","沈阳桃仙机场","抵达",41.637010,123.486593,"沈阳市浑南区桃仙街道","#356f67","11:15","只带随身行李，三人直接网约车前往清河半岛，减少换乘。",[["交通","网约车优先"],["提醒","航班时刻以订单为准"],["地图坐标","OpenStreetMap"]]),
    p("qinghe","清河半岛温泉","温泉体验",41.933779,123.427358,"沈北新区蒲南路20号","#df765e","13:00","把东北洗浴体验放在第一天，下午先泡、晚上私汤，恢复体力。",[["房型","主楼 5 楼双床温泉套房"],["床型","2 × 1.8m"],["订单核对","四早四票 / 3 成人"],["避雷","不住公共休息区"]],"warm"),
    p("room","豪华双床温泉套房","安静过夜",41.933930,123.427640,"清河半岛主楼 5 楼","#d6a54b","15:00","两张大床让三人同住但不拥挤；主楼电梯上下温泉，不走别墅区。",[["参考价","约 ¥2,100–2,200"],["早餐","订单称含四早"],["温泉","订单称含四票"],["注意","以付款页权益为准"]],"warm")],
    timeline:[["11:15","抵达桃仙机场","仅带随身行李，直接网约车"],["13:00","清河半岛入场","先泡户外池 / 轻松拍照"],["15:00","办理入住","检查房间与私汤清洁"],["17:30","三楼单点晚餐","不默认自助开放"],["21:00","夜泡后回房","私汤收尾，早睡恢复"]]},
  D2:{title:"D2 · 盛京旧城",caption:"用一条步行友好的历史主轴，串起清代宫殿、民国府邸和中街烟火。",nodes:[
    p("atour","中街故宫亚朵 S","市区住宿",41.795700,123.448800,"沈河区朝阳街127号","#356f67","上午","位于故宫、帅府和中街步行圈；选择 1.8m + 1.2m 尊享家庭房，睡眠与便利优先。",[["入住","9/11–9/13"],["房型","1.8m + 1.2m"],["备注","高楼层 / 无烟 / 远离电梯"],["备选","希尔顿惠庭"]]),
    p("palace","沈阳故宫","清初皇宫",41.796113,123.449644,"沈河区沈阳路171号","#d6a54b","10:00","盛京历史的核心。大政殿、十王亭与凤凰楼让清初宫廷从课本变成实景。",[["开放基线","08:30–17:00"],["停止入馆","16:15"],["预约","官方渠道 / 身份证"],["讲解","推荐"],["资料来源","沈阳故宫官网"]]),
    p("marshal","张氏帅府","民国建筑群",41.792111,123.451670,"沈河区朝阳街少帅府巷46号","#df765e","13:30","从清代皇宫接到张作霖、张学良的近代史；通票还能看赵一荻故居与金融馆。",[["建议","通票按顺序逛完"],["看点","大青楼 / 老虎厅"],["讲解","推荐"],["提醒","出馆后不能再入"]]),
    p("zhongjie","中街","老城烟火",41.798969,123.454381,"沈河区中街路","#356f67","16:30","在历史参观后轻松收尾；中街冰点、老边饺子和老四季均可按胃口选择。",[["甜品","中街冰点一楼"],["晚餐","老四季候选"],["避雷","主街网红小吃溢价"],["交通","步行优先"]])],
    timeline:[["09:30","离开清河半岛","市区酒店寄存 / 不强赶早市"],["10:00","沈阳故宫","开门入场，建议讲解"],["12:30","老边饺子","三人共享，坐下慢吃"],["13:30","张氏帅府","连赵一荻故居、金融馆"],["16:30","中街散步","冰点 / 老四季，回酒店休息"]]},
  D3:{title:"D3 · 历史与西塔",caption:"一日从历史记忆走进铁西工业，再以西塔美食温柔收尾。",nodes:[
    p("918","九一八历史博物馆","历史记忆",41.834199,123.461502,"大东区望花南街46号","#2e4758","09:00","沈阳最有历史分量的地点之一，建议以讲解理解时间线，肃穆参观。",[["开放基线","09:00–17:00"],["停止入馆","16:30"],["预约","易游沈阳"],["讲解","推荐"],["资料来源","辽宁文旅页面"]],"dark"),
    p("industry","中国工业博物馆","铁西工业",41.818950,123.349191,"铁西区卫工北街14号","#df765e","11:45","巨型机床、铸造设备和厂房空间，是沈阳工业城市记忆最直观的入口。",[["门票","通常免费"],["预约","公众号 / 美团核验"],["看点","机床 / 铸造馆"],["穿着","舒适鞋"]]),
    p("1905","1905 文创园","旧厂房短歇",41.809895,123.376247,"铁西区兴华北街8号","#d6a54b","14:30","不把它当重景点；在旧厂房喝咖啡、拍照、歇脚，再去西塔。",[["作用","短歇 / 咖啡"],["节奏","不久留"],["画面","厂房工业风"],["提醒","看当日营业"]]),
    p("xita","西塔朝鲜族风情街","晚间美食",41.802444,123.402405,"和平区西塔街 / 安图街一带","#356f67","17:00","这是全程最强美食夜。先买可能售罄的打糕，再用共享鳗鱼作为主餐。",[["先买","师任堂打糕 / 饭团"],["主餐","味家烤鳗鱼共享"],["加餐","最多1–2份"],["避雷","不做7店通关"]])],
    timeline:[["09:00","九一八历史博物馆","预约后入馆，建议讲解"],["11:45","中国工业博物馆","控制在 1.5–2 小时"],["14:30","1905 文创园","咖啡 / 拍照 / 短歇"],["17:00","西塔先买打糕","热门款可能售罄"],["17:30","西塔主餐","鳗鱼主餐 + 少量共享加餐"]]},
  D4:{title:"D4 · 轻松返程",caption:"不硬塞景点；睡到自然醒、买好伴手礼，然后从容前往机场。",nodes:[
    p("hotelout","市区酒店退房","慢启动",41.795700,123.448800,"沈河区朝阳街127号","#356f67","上午","最后一天不赶早；退房后寄存行李，轻装逛中街。",[["退房","12:00前为准"],["行李","前台寄存"],["原则","不排远景点"],["状态","轻松收尾"]]),
    p("souvenir","中街伴手礼","本地味道",41.798969,123.454381,"沈河区中街路","#d6a54b","中午","买不老林糖、克拉古斯香肠、八王寺汽水等；正规超市或老字号更稳。",[["推荐","不老林 / 八王寺"],["冷链","香肠按返程时间买"],["避雷","景区花哨礼盒"],["原则","不要买散装无标识"]]),
    p("return","沈阳桃仙机场","返程",41.637010,123.486593,"浑南区桃仙街道","#2e4758","15:30","预留充足时间，直飞返宁。中街地铁需在青年大街换乘 2 号线；三人优先打车也可。",[["航班","HO1712 候选"],["起飞","18:35"],["交通","地铁换乘或打车"],["提醒","时刻以订单为准"]],"dark")],
    timeline:[["上午","睡到自然醒","退房、寄存行李"],["中午","中街伴手礼","不老林 / 八王寺等"],["15:30","前往桃仙机场","预留值机与安检时间"],["18:35","沈阳 → 南京","HO1712 候选直飞"]]}
};
let selectedDay="D1", selectedNode=null;
const map=L.map("route-map",{scrollWheelZoom:true}).setView([41.81,123.42],11);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);
const overlay=d3.select(map.getPanes().overlayPane).append("svg").attr("class","d3-map-overlay");
const routeLayer=overlay.append("g").attr("class","leaflet-zoom-hide");
function detail(node,day){const b=node||{name:days[day].title,kind:"整日概览",why:days[day].caption,facts:[["操作","点击地图圆点"],["路线","按时间顺序浏览"],["地图","按真实经纬度呈现"],["状态","动态信息待核验"]]};const f=[["地址",b.address],...b.facts].filter(x=>x[1]).map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");document.querySelector("#detail-card").innerHTML=`<div class="detail-hero ${b.tone||""}"><span class="detail-tag">${b.kind}</span><h2>${b.name}</h2></div><h3>为什么安排在这里</h3><p>${b.why}</p><span class="status">● ${node?"地点已选中":"整日路线"}</span><div class="detail-facts">${f}</div><h3>温馨提示</h3><p>地图用于理解位置与路线关系；虚线不是导航路径。时间、门票和营业状态以出发前的订单页、官方预约页为准。</p>`;}
function timeline(day){document.querySelector("#timeline").innerHTML=days[day].timeline.map(t=>`<li><time>${t[0]}</time><i></i><div><b>${t[1]}</b><span>${t[2]}</span></div></li>`).join("");}
function draw(){const nodes=days[selectedDay].nodes, pts=nodes.map(n=>map.latLngToLayerPoint([n.lat,n.lng])), b=map.getBounds(),nw=map.latLngToLayerPoint(b.getNorthWest()),se=map.latLngToLayerPoint(b.getSouthEast());overlay.attr("width",se.x-nw.x).attr("height",se.y-nw.y).style("left",`${nw.x}px`).style("top",`${nw.y}px`);routeLayer.attr("transform",`translate(${-nw.x},${-nw.y})`);routeLayer.selectAll("path.edge").data(d3.pairs(pts)).join("path").attr("class","edge").attr("d",d=>`M${d[0].x},${d[0].y} L${d[1].x},${d[1].y}`);routeLayer.selectAll("text.route-edge-label").data(d3.pairs(pts)).join("text").attr("class","route-edge-label").attr("x",d=>(d[0].x+d[1].x)/2).attr("y",d=>(d[0].y+d[1].y)/2-10).text((_,i)=>i===0?"推荐交通":"下一站");const gs=routeLayer.selectAll("g.node").data(nodes,n=>n.id),en=gs.enter().append("g").attr("class","node").style("opacity",0).on("click",(_,n)=>{selectedNode=n;detail(n,selectedDay);draw();});en.append("circle");en.append("text").attr("class","node-title").attr("text-anchor","middle");en.append("text").attr("class","node-time").attr("text-anchor","middle");const all=en.merge(gs);all.attr("transform",(_,i)=>`translate(${pts[i].x},${pts[i].y})`).transition().duration(250).style("opacity",1);all.select("circle").attr("r",n=>selectedNode?.id===n.id?24:18).attr("fill",n=>n.color);all.select(".node-title").attr("y",-28).text(n=>n.name);all.select(".node-time").attr("y",39).text(n=>n.time);gs.exit().remove();}
function render(day){selectedDay=day;selectedNode=null;document.querySelector("#day-title").textContent=days[day].title;document.querySelector("#route-caption").textContent=`${days[day].caption} 地点按真实坐标标出，虚线仅表示推荐移动顺序。`;document.querySelectorAll(".day-tab").forEach(b=>b.classList.toggle("active",b.dataset.day===day));timeline(day);detail(null,day);map.fitBounds(L.latLngBounds(days[day].nodes.map(n=>[n.lat,n.lng])).pad(.18),{animate:true,duration:.65,maxZoom:13});setTimeout(draw,700);}
map.on("moveend zoomend",draw);document.querySelectorAll(".day-tab").forEach(b=>b.addEventListener("click",()=>render(b.dataset.day)));document.querySelector("#reset-selection").addEventListener("click",()=>{selectedNode=null;detail(null,selectedDay);draw();});render("D1");
