/*
 * 旅行数据源：新增地点、日期或分类时只编辑本文件。
 * node.categories 可同时属于多个类别；day.stops 只引用 node id。
 */
window.TRIP_CONFIG={
  meta:{title:"沈阳四日游",dates:"2026.09.10—09.13",home:"南京",city:"沈阳",currency:"CNY"},
  categories:{transport:"交通",stay:"住宿",food:"餐饮",experience:"体验"},
  nodes:{
    nkg:{name:"南京禄口机场",categories:["transport"],lat:31.7354,lng:118.8620,address:"南京市江宁区翔鹰三路",short:"08:55 起飞 · 南京出发",intro:"全程只带随身行李，建议提前两小时抵达。",why:"把抵达沈阳后的体力留给温泉，选择上午直飞。",facts:[["航班候选","MU2827"],["起飞","08:55"],["行李","仅随身行李"]],price:"机票另计",color:"#3f6e8a",tone:"dark"},
    airport:{name:"沈阳桃仙机场",categories:["transport"],lat:41.637010,lng:123.486593,address:"沈阳市浑南区桃仙街道",short:"11:15 落地 · 直接去温泉",intro:"这趟旅程的沈阳起终点。第一天不安排市区，抵达后直接去清河半岛；返程日留足值机时间。",why:"减少初到城市的换乘和赶路。",facts:[["抵达候选","11:15"],["去温泉","网约车约 40–50 分钟"],["返程候选","HO1712 18:35"]],price:"机票另计",color:"#3f6e8a",tone:"dark"},
    qinghe:{name:"清河半岛温泉",categories:["experience","food"],lat:41.933779,lng:123.427358,address:"沈北新区蒲南路20号",short:"泡汤、汗蒸、轻晚餐",intro:"大型温泉与水乐园综合体；行程把它放在第一天，只保留泡汤、吃饭和休息，不把体验排成打卡。",why:"落地后最需要的是恢复体力，而不是赶景点。",facts:[["看点","户外温泉 / 无边池 / 汗蒸"],["餐饮","三楼单点优先"],["提醒","不默认有自助餐"]],price:"已计入套房",color:"#dc795d",tone:"warm"},
    qingheRoom:{name:"清河半岛主楼套房",categories:["stay"],lat:41.933930,lng:123.427640,address:"清河半岛主楼 5 楼",short:"15:00 入住 · 两张大床",intro:"主楼客房的价值是泡完温泉可直接乘电梯回房；避免公共休息区，也不用往返别墅区。",why:"三人同住且安静优先，因此选两张 1.8m 大床。",facts:[["床型","2 × 1.8m"],["早餐","订单称含四早"],["温泉","订单称含四票"],["核对","以付款页权益为准"]],price:"¥2,100–2,200",color:"#c99d45",tone:"warm"},
    atour:{name:"中街故宫亚朵 S",categories:["stay"],lat:41.795700,lng:123.448800,address:"沈河区朝阳街127号",short:"市区两晚 · 步行到故宫",intro:"市区两晚住在故宫、中街与帅府的步行圈。酒店不是打卡重点，而是每天随时可回房休息的基地。",why:"连锁品牌、家庭房、位置和睡眠质量之间最均衡。",facts:[["入住","9/11–9/13"],["房型","1.8m + 1.2m"],["备注","高楼层 / 无烟 / 远离电梯"]],price:"约 ¥650–850 / 晚",color:"#3f806d"},
    xiaoheyan:{name:"小河沿早市",categories:["food","experience"],lat:41.777211,lng:123.467924,address:"沈河区小河沿路一带",short:"早市早餐 · 9 点前最热闹",intro:"沈阳典型早市，适合作为温泉后进入市区的第一餐。",why:"市井感强，但只吃一两样，保留胃口给中街午餐。",facts:[["推荐","豆腐脑 / 油炸糕 / 豆浆"],["时间","建议 08:00 左右"],["提醒","卫生看摊、别囤太多"]],price:"约 ¥60–100",color:"#dc795d"},
    palace:{name:"沈阳故宫",categories:["experience"],lat:41.796113,lng:123.449644,address:"沈河区沈阳路171号",short:"清初皇宫 · 建议讲解",intro:"清朝入关前的皇宫，规模紧凑却有鲜明的满族宫廷布局；大政殿、十王亭与凤凰楼是主线。",why:"盛京历史的核心，值得用讲解把建筑和人物串起来。",facts:[["开放基线","08:30–17:00"],["停止入馆","16:15"],["预约","官方渠道 / 身份证"],["建议","开门入场 + 讲解"]],price:"门票另计",color:"#c99d45"},
    oldEdge:{name:"老边饺子",categories:["food"],lat:41.798344,lng:123.453165,address:"中街商圈（以预订门店为准）",short:"坐下慢吃的午餐",intro:"老字号饺子适合故宫后的正餐，重点是坐下慢吃，而不是排多个网红摊。",why:"在历史参观之间留出真正休息的一餐。",facts:[["建议","煸馅饺子 / 冰花煎饺"],["人均","约 ¥50–60"],["提醒","门店与排队当日复核"]],price:"约 ¥150–180",color:"#dc795d"},
    marshal:{name:"张氏帅府",categories:["experience"],lat:41.792111,lng:123.451670,address:"沈河区朝阳街少帅府巷46号",short:"民国建筑群 · 推荐讲解",intro:"张作霖、张学良旧居，把沈阳近代史从书本拉到现场；大青楼和老虎厅是重点。",why:"与故宫形成从清代到民国的完整叙事。",facts:[["建议","通票按顺序逛完"],["看点","大青楼 / 老虎厅"],["讲解","推荐"],["提醒","出馆后通常不可再入"]],price:"门票另计",color:"#dc795d"},
    zhongjie:{name:"中街",categories:["food","experience"],lat:41.798969,lng:123.454381,address:"沈河区中街路",short:"冰点、晚餐、散步",intro:"老城最方便的散步与吃饭区域，不需要把所有小吃都打卡。",why:"把历史线用轻松的晚间步行收尾，也离酒店很近。",facts:[["甜品","中街冰点一楼"],["晚餐","老四季候选"],["避雷","主街网红小吃溢价"]],price:"约 ¥180–260",color:"#3f806d"},
    museum918:{name:"九一八历史博物馆",categories:["experience"],lat:41.834199,lng:123.461502,address:"大东区望花南街46号",short:"肃穆参观 · 建议讲解",intro:"围绕九一八事变建立的纪念馆；重点是通过讲解理解时间线，而不是追求打卡数量。",why:"沈阳最有历史分量的地点之一，上午安排更完整。",facts:[["开放基线","09:00–17:00"],["停止入馆","16:30"],["预约","易游沈阳"],["提醒","带身份证，不摆拍"]],price:"免费预约",color:"#344f61",tone:"dark"},
    industry:{name:"中国工业博物馆",categories:["experience"],lat:41.818950,lng:123.349191,address:"铁西区卫工北街14号",short:"巨型机床与厂房",intro:"工业遗存和大型设备构成的实景博物馆，空间尺度感很强。",why:"这是保留铁西线的原因：能直观看见沈阳工业城市的记忆。",facts:[["门票","通常免费"],["预约","公众号 / 美团当周复核"],["穿着","舒适鞋"],["节奏","控制在 2 小时内"]],price:"通常免费",color:"#dc795d"},
    park1905:{name:"1905 文创园",categories:["experience","food"],lat:41.809895,lng:123.376247,address:"铁西区兴华北街8号",short:"咖啡、拍照、短歇",intro:"由老厂房改造而来，咖啡、展览和小店共存。",why:"只做一次短歇，转换节奏，不占掉西塔晚餐体力。",facts:[["作用","短歇 / 咖啡"],["画面","旧厂房工业风"],["提醒","看当日营业"]],price:"约 ¥60–100",color:"#c99d45"},
    xita:{name:"西塔朝鲜族风情街",categories:["food","experience"],lat:41.802444,lng:123.402405,address:"和平区西塔街 / 安图街一带",short:"打糕、烤鳗鱼、晚餐",intro:"沈阳朝鲜族风味最集中的街区。先买热门打糕，再以共享烤鳗鱼做主餐即可。",why:"把全程最值得专门安排的一顿晚餐留给夜晚的西塔。",facts:[["先买","师任堂打糕 / 饭团"],["主餐","味家烤鳗鱼共享"],["加餐","最多 1–2 份"],["避雷","不做七店通关 / 避拉客店"]],price:"约 ¥500–650",color:"#3f806d"},
    souvenir:{name:"中街伴手礼",categories:["experience"],lat:41.798969,lng:123.454381,address:"沈河区中街路",short:"不老林、八王寺等",intro:"只买包装和生产信息明确的本地品牌，冷链食品临近出发再买。",why:"返程日只留轻松活动，不为多去一个景点制造焦虑。",facts:[["推荐","不老林 / 八王寺"],["冷链","香肠临近出发买"],["避雷","景区花哨礼盒"]],price:"按实际购买",color:"#c99d45"}
  },
  days:[
    {id:"D1",date:"9/10 周四",title:"温泉",summary:"从南京飞抵沈阳，直接去清河半岛，把第一天留给泡汤、吃饭和安静睡一晚。",stay:"清河半岛主楼 5 楼豪华双床温泉套房",stayNode:"qingheRoom",dailyBudget:"¥2,100–2,200",note:"套房订单若明确含四张温泉票与四份早餐，不再另购三人温泉票。",view:{lng:123.46,lat:41.79,zoom:10},stops:[{node:"nkg",time:"06:55",type:"point",detail:"抵达禄口机场，办理安检",mode:"出发"},{node:"airport",time:"11:15",type:"point",detail:"MU2827 候选抵达桃仙",mode:"直飞",duration:"2小时20分"},{node:"qinghe",time:"13:00",type:"block",stay:"9小时",detail:"泡汤、汗蒸、晚餐与夜泡",mode:"网约车",duration:"40–50分钟"}]},
    {id:"D2",date:"9/11 周五",title:"盛京旧城",summary:"温泉后不赶早：舒舒服服退房、进城，再走故宫、帅府与中街。",stay:"中街故宫亚朵 S · 尊享家庭房",stayNode:"atour",dailyBudget:"¥650–850",note:"市区酒店为两晚连住；门票与餐饮另计。",view:{lng:123.451,lat:41.796,zoom:14},stops:[{node:"palace",time:"11:00",type:"block",stay:"2小时15分",detail:"大政殿、十王亭、凤凰楼；建议讲解",mode:"网约车",duration:"约 1 小时"},{node:"oldEdge",time:"13:30",type:"block",stay:"50分钟",detail:"饺子午餐，坐下慢吃",mode:"步行",duration:"10分钟"},{node:"marshal",time:"14:30",type:"block",stay:"1小时45分",detail:"大青楼、老虎厅；建议讲解",mode:"步行",duration:"8分钟"},{node:"zhongjie",time:"16:30",type:"block",stay:"4小时",detail:"冰点、晚餐、散步；不追网红小吃",mode:"步行",duration:"8分钟"}]},
    {id:"D3",date:"9/12 周六",title:"历史与西塔",summary:"早市只吃一小轮；上午九一八，下午铁西，傍晚把胃口留给西塔。",stay:"中街故宫亚朵 S · 尊享家庭房",stayNode:"atour",dailyBudget:"¥650–850",note:"预约与餐饮另计；1905 只做短歇。",view:{lng:123.405,lat:41.817,zoom:12},stops:[{node:"xiaoheyan",time:"07:30",type:"block",stay:"45分钟",detail:"豆腐脑、油炸糕；适量吃",mode:"网约车",duration:"15分钟"},{node:"museum918",time:"09:00",type:"block",stay:"2小时",detail:"肃穆参观、听讲解",mode:"网约车",duration:"20分钟"},{node:"industry",time:"11:45",type:"block",stay:"2小时",detail:"机床、铸造馆、厂房",mode:"网约车",duration:"35分钟"},{node:"park1905",time:"14:30",type:"block",stay:"1小时15分",detail:"咖啡、拍照、短歇",mode:"网约车",duration:"12分钟"},{node:"xita",time:"17:00",type:"block",stay:"3小时30分",detail:"师任堂打糕、共享鳗鱼、少量加餐",mode:"网约车",duration:"20分钟"}]},
    {id:"D4",date:"9/13 周日",title:"轻松返程",summary:"睡到自然醒，买好伴手礼，预留充足机场时间。",stay:"中午退房 · 前台寄存行李",dailyBudget:"¥250–450",note:"伴手礼按实际购买；不再硬塞景点。",view:{lng:123.47,lat:41.72,zoom:10},stops:[{node:"souvenir",time:"11:00",type:"block",stay:"2小时",detail:"买伴手礼、轻午餐",mode:"步行",duration:"10分钟"},{node:"airport",time:"15:30",type:"point",detail:"值机、安检、登机",mode:"网约车",duration:"40–60分钟"}]}
  ]
};
